# --------------- python用 --------------
[[plugins]]  # deoplete.nvim source for jedi
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = 'python'
on_i = 1
hook_add ='''
    let g:deoplete#sources#jedi#python_path = $PYENV_ROOT.'/versions/3.7.6/envs/neovim3/bin/python3'
'''

[[plugins]]  # deoplete.nvim source for jedi
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
on_i = 1

